name: Build and test

on:
  push:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  linux:
    strategy:
      matrix:
        rust: [ 1.39.0, stable, beta, nightly ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      env:
        RUST_VERSION: ${{matrix.rust}}
      run: |
        sudo apt-get install -y libfreetype-dev
        cargo test --all

  macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      run: cargo test --all

  windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      run: cargo test --all
